image: hypriot/drone_builder_base:latest
git:
  path: github.com/hypriot/rpi-noobs-builder

script:
  - aws s3 --region eu-central-1 cp s3://buildserver-production/images/hypriot-rpi-`cat VERSION`.img.zip .
  - wget -q --content-disposition http://downloads.raspberrypi.org/NOOBS_lite_latest
  - ./create.sh
  - echo "#####################\n***** COMPLETED *****\n#####################"

publish:
  s3:
    acl: public-read
    region: eu-central-1
    bucket: buildserver-production
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: result/
    target: noobs/
    recursive: true
